/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sz.panel;

/**
 *
 * @author ADVAN
 */
import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class GrafikPenjualan extends javax.swing.JPanel {
    // List untuk menampung data dari database
    private final List<Double> dataPendapatan = new ArrayList<>();
    private final List<String> dataTanggal = new ArrayList<>();

    public GrafikPenjualan() {
        initComponents();
        // Konfigurasi Spinner Tanggal
        spinnerMulai.setModel(new javax.swing.SpinnerDateModel());
        spinnerSampai.setModel(new javax.swing.SpinnerDateModel());
        spinnerMulai.setEditor(new javax.swing.JSpinner.DateEditor(spinnerMulai, "yyyy-MM-dd"));
        spinnerSampai.setEditor(new javax.swing.JSpinner.DateEditor(spinnerSampai, "yyyy-MM-dd"));
        
        // Memastikan pnlGrafik menggunakan BorderLayout agar gambar fleksibel
        pnlGrafik.setLayout(new java.awt.BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlGrafik = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (dataPendapatan.size() < 2) {
                    g.drawString("Data tidak cukup untuk grafik (minimal 2 hari)", 20, 20);
                    return;
                }

                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                int pad = 40; // Jarak dari pinggir panel
                int w = getWidth() - 2 * pad;
                int h = getHeight() - 2 * pad;

                // Cari nilai tertinggi untuk menentukan skala tinggi grafik
                double maxPendapatan = 0;
                for (Double v : dataPendapatan) if (v > maxPendapatan) maxPendapatan = v;

                double xDiv = (double) w / (dataPendapatan.size() - 1);
                double yDiv = (double) h / maxPendapatan;

                // Gambar Garis Penghubung
                g2.setColor(new Color(0, 102, 204)); // Warna Biru
                g2.setStroke(new BasicStroke(3f));

                for (int i = 0; i < dataPendapatan.size() - 1; i++) {
                    int x1 = pad + (int) (i * xDiv);
                    int y1 = (getHeight() - pad) - (int) (dataPendapatan.get(i) * yDiv);
                    int x2 = pad + (int) ((i + 1) * xDiv);
                    int y2 = (getHeight() - pad) - (int) (dataPendapatan.get(i + 1) * yDiv);

                    g2.drawLine(x1, y1, x2, y2);
                    g2.fillOval(x1 - 4, y1 - 4, 8, 8); // Titik point
                }
                // Titik terakhir
                g2.fillOval(pad + (int)((dataPendapatan.size()-1)*xDiv) - 4,
                    (getHeight() - pad) - (int)(dataPendapatan.get(dataPendapatan.size()-1)*yDiv) - 4, 8, 8);

                // Gambar Garis Sumbu (Axis)
                g2.setColor(Color.BLACK);
                g2.setStroke(new BasicStroke(1f));
                g2.drawLine(pad, getHeight() - pad, getWidth() - pad, getHeight() - pad); // Garis X
                g2.drawLine(pad, pad, pad, getHeight() - pad); // Garis Y
            }
        };
        btnCari = new javax.swing.JButton();
        spinnerSampai = new javax.swing.JSpinner();
        spinnerMulai = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRAFIK PENJUALAN");

        pnlGrafik.setBackground(new java.awt.Color(153, 255, 255));
        pnlGrafik.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane2.setViewportView(pnlGrafik);

        btnCari.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        spinnerSampai.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        spinnerSampai.setModel(new javax.swing.SpinnerDateModel());

        spinnerMulai.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        spinnerMulai.setModel(new javax.swing.SpinnerDateModel());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("S/D");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinnerMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(spinnerSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 121, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerMulai)
                    .addComponent(spinnerSampai)
                    .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(180, 180, 180)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        ambilDataDanGambar();
    }//GEN-LAST:event_btnCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlGrafik;
    private javax.swing.JSpinner spinnerMulai;
    private javax.swing.JSpinner spinnerSampai;
    // End of variables declaration//GEN-END:variables
private void ambilDataDanGambar() {
    dataPendapatan.clear();
    dataTanggal.clear();
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String mulai = sdf.format(spinnerMulai.getValue());
    String sampai = sdf.format(spinnerSampai.getValue());

    try {
        // Query untuk mendapatkan total pendapatan per hari
        String sql = "SELECT tanggal, SUM(total) AS total_harian FROM transaksi " +
                     "WHERE tanggal BETWEEN '" + mulai + "' AND '" + sampai + "' " +
                     "GROUP BY tanggal ORDER BY tanggal ASC";
        
        Connection conn = sz.util.Koneksi.Go();
        Statement stm = conn.createStatement();
        ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            dataPendapatan.add(res.getDouble("total_harian"));
            dataTanggal.add(res.getString("tanggal"));
        }
        
        // Perintah untuk menggambar ulang grafik di panel
        pnlGrafik.repaint(); 

    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal ambil data: " + e.getMessage());
    }
}}
