/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sz.panel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADVAN
 */
public class Nota extends javax.swing.JPanel {

    /**
     * Creates new form Nota
     */
    public Nota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();
        btnCetak = new javax.swing.JButton();

        txtNota.setColumns(20);
        txtNota.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtNota.setRows(5);
        jScrollPane1.setViewportView(txtNota);

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnCetak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCetak)
                .addGap(0, 15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try {
        boolean complete = txtNota.print(); // Memanggil dialog print sistem
        if (complete) {
            JOptionPane.showMessageDialog(this, "Cetak Selesai!");
        }
    } catch (java.awt.print.PrinterException e) {
        JOptionPane.showMessageDialog(this, "Gagal Cetak: " + e.getMessage());
    }
    }//GEN-LAST:event_btnCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtNota;
    // End of variables declaration//GEN-END:variables
public void isiNota(String id, String tgl, String kasir, javax.swing.table.DefaultTableModel model, String total) {
    txtNota.setText("");
    txtNota.append("          SHOESZONE STORE          \n");
    txtNota.append("    Kualitas Melangkah Bersama     \n");
    txtNota.append("  Jl. Gajah Mada No. 123, Tegal    \n");
    txtNota.append("===================================\n");
    txtNota.append(" No. Nota : " + id + "\n");
    txtNota.append(" Kasir    : " + kasir + "\n");
    txtNota.append(" Tanggal  : " + tgl + "\n");
    txtNota.append("===================================\n");

    // Header Tabel Manual
    txtNota.append(String.format("%-18s %-3s %-10s\n", "Item", "Qty", "Subtotal"));
    txtNota.append("-----------------------------------\n");

    // Looping data dari keranjang
    for (int i = 0; i < model.getRowCount(); i++) {
        String nama = model.getValueAt(i, 1).toString();
        String qty  = model.getValueAt(i, 3).toString();
        String sub  = model.getValueAt(i, 4).toString();

        // Jika nama produk terlalu panjang, potong agar tidak merusak baris
        if (nama.length() > 18) {
            nama = nama.substring(0, 15) + "...";
        }

        // Format: Nama (18 char), Qty (3 char), Subtotal (10 char)
        txtNota.append(String.format("%-18s %-3s %-10s\n", nama, qty, sub));
    }

    txtNota.append("===================================\n");
    txtNota.append(String.format("%-22s: %s\n", "GRAND TOTAL", total));
    txtNota.append("===================================\n");
    txtNota.append("\n");
    txtNota.append("     Terima Kasih Atas Kunjungan    \n");
    txtNota.append("    Barang yang sudah dibeli tidak  \n");
    txtNota.append("       dapat ditukar/dikembalikan   \n");
    
    // Kunci teks agar tidak bisa diedit user
    txtNota.setEditable(false);
}
}
