/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sz.panel;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sz.util.Koneksi;

/**
 *
 * @author ADVAN
 */
public class Transaksi extends javax.swing.JPanel {

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        lblTotal.setText("Total : Rp 0");
        initTransaksi();
        loadProduk();
        setAutoID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdTransaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnSimpanTransaksi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Transaksi");

        txtIdTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal");

        txtTanggal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlabel.setForeground(new java.awt.Color(255, 255, 255));
        jlabel.setText("Alamat");

        txtAlamat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        tblProduk.setBackground(new java.awt.Color(51, 255, 255));
        tblProduk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nama", "ukuran", "harga", "stok"
            }
        ));
        tblProduk.setRowHeight(30);
        tblProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduk);
        if (tblProduk.getColumnModel().getColumnCount() > 0) {
            tblProduk.getColumnModel().getColumn(0).setHeaderValue("id");
            tblProduk.getColumnModel().getColumn(1).setHeaderValue("nama");
            tblProduk.getColumnModel().getColumn(2).setHeaderValue("ukuran");
            tblProduk.getColumnModel().getColumn(3).setHeaderValue("harga");
            tblProduk.getColumnModel().getColumn(4).setHeaderValue("stok");
        }

        btnTambah.setBackground(new java.awt.Color(0, 255, 255));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.setBorderPainted(false);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.setBorderPainted(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        tblKeranjang.setBackground(new java.awt.Color(51, 255, 255));
        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nama", "harga", "jumlah", "subtotal"
            }
        ));
        jScrollPane2.setViewportView(tblKeranjang);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setText("total");

        btnSimpanTransaksi.setBackground(new java.awt.Color(51, 255, 255));
        btnSimpanTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSimpanTransaksi.setText("Simpan");
        btnSimpanTransaksi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSimpanTransaksi.setBorderPainted(false);
        btnSimpanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnSimpanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(203, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Transaksi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cari");

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah");

        txtJumlah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(118, 118, 118)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIdTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                            .addComponent(txtTanggal))
                                        .addGap(94, 94, 94)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                            .addComponent(txtAlamat)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdukMouseClicked

    }//GEN-LAST:event_tblProdukMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    
    int row = tblProduk.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih produk terlebih dahulu!");
        return;
    }

    if (txtJumlah.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Jumlah belum diisi!");
        return;
    }

    int jumlah = Integer.parseInt(txtJumlah.getText());

    DefaultTableModel modelProduk =
            (DefaultTableModel) tblProduk.getModel();

    // AMBIL DATA SESUAI STRUKTUR BARU
    int idProduk = Integer.parseInt(
            modelProduk.getValueAt(row, 0).toString()
    );
    String namaProduk =
            modelProduk.getValueAt(row, 1).toString();
    double harga = Double.parseDouble(
            modelProduk.getValueAt(row, 3).toString()
    );

    double subtotal = harga * jumlah;

    DefaultTableModel modelKeranjang =
            (DefaultTableModel) tblKeranjang.getModel();

    modelKeranjang.addRow(new Object[]{
        idProduk,
        namaProduk,
        formatRupiah(harga),
        jumlah,
        formatRupiah(subtotal)
    });

    hitungTotal();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanTransaksiActionPerformed
        // A. Validasi Awal
    if (tblKeranjang.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Keranjang kosong!");
        return;
    }
    if (txtNama.getText().isEmpty() || txtAlamat.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama & Alamat harus diisi!");
        return;
    }

    Connection con = null;
    try {
        con = Koneksi.Go();
        con.setAutoCommit(false); 

        // 1. SIMPAN PELANGGAN
        String sqlPlg = "INSERT INTO pelanggan (nama_pelanggan, alamat) VALUES (?, ?)";
        PreparedStatement psPlg = con.prepareStatement(sqlPlg, Statement.RETURN_GENERATED_KEYS);
        psPlg.setString(1, txtNama.getText());
        psPlg.setString(2, txtAlamat.getText());
        psPlg.executeUpdate();
        
        ResultSet rsP = psPlg.getGeneratedKeys();
        rsP.next();
        int idPlg = rsP.getInt(1);

        // 2. SIMPAN TRANSAKSI
        // PENTING: Pastikan jLabel1 di dashboard tidak kosong
        String kasir = sz.util.Users.getNama(); 
        String sqlTrx = "INSERT INTO transaksi (id_pelanggan, nama_kasir, tanggal, total) VALUES (?, ?, NOW(), ?)";
        PreparedStatement psTrx = con.prepareStatement(sqlTrx, Statement.RETURN_GENERATED_KEYS);
        psTrx.setInt(1, idPlg);
        psTrx.setString(2, kasir);
        psTrx.setDouble(3, ambilTotalDariLabel());
        psTrx.executeUpdate();
        
        ResultSet rsT = psTrx.getGeneratedKeys();
        rsT.next();
        int idTrx = rsT.getInt(1);

        // 3. SIMPAN DETAIL & UPDATE STOK
        DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            int idProd = Integer.parseInt(model.getValueAt(i, 0).toString());
            int qty = Integer.parseInt(model.getValueAt(i, 3).toString());
            double sub = Double.parseDouble(model.getValueAt(i, 4).toString().replace(".", "").replace(",", ""));

            // Insert Detail
            PreparedStatement psD = con.prepareStatement("INSERT INTO detail_transaksi (id_transaksi, id_produk, jumlah, subtotal) VALUES (?,?,?,?)");
            psD.setInt(1, idTrx);
            psD.setInt(2, idProd);
            psD.setInt(3, qty);
            psD.setDouble(4, sub);
            psD.executeUpdate();

            // Update Stok
            PreparedStatement psS = con.prepareStatement("UPDATE produk SET stok = stok - ? WHERE id_produk = ?");
            psS.setInt(1, qty);
            psS.setInt(2, idProd);
            psS.executeUpdate();
        }

        con.commit(); // Berhasil simpan semua!

        // 4. PINDAH KE PANEL NOTA (Solusi BorderLayout)
            Nota pnlNota = new Nota();
            pnlNota.isiNota(
                String.valueOf(idTrx), 
                txtTanggal.getText(), 
                kasir, // Variabel kasir dari Users.getNama()
                model, 
                lblTotal.getText()
            );

        java.awt.Container parent = this.getParent();
        parent.removeAll();
        parent.add(pnlNota, java.awt.BorderLayout.CENTER);
        parent.revalidate();
        parent.repaint();

    } catch (NumberFormatException | SQLException e) {
        try { if(con!=null) con.rollback(); } catch(SQLException ex){}
        JOptionPane.showMessageDialog(this, "Sistem Error: " + e.getMessage());
        e.printStackTrace(); 
    }
    }//GEN-LAST:event_btnSimpanTransaksiActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
 // 1. Ambil baris yang dipilih oleh user di tabel keranjang
    int row = tblKeranjang.getSelectedRow();
    
    // 2. Cek apakah ada baris yang dipilih
    if (row != -1) {
        DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
        
        // 3. Konfirmasi penghapusan (Opsional, agar tidak sengaja terhapus)
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Hapus item ini dari keranjang?", "Konfirmasi", 
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // 4. Hapus baris dari model tabel
            model.removeRow(row);
            
            // 5. PENTING: Hitung ulang total belanjaan
            updateTotalKeuntungan(); 
        }
    } else {
        // Jika user klik tombol hapus tapi belum pilih baris di tabel
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih item di tabel keranjang yang ingin dihapus!");
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        String kunci = txtCari.getText();
    if (kunci.isEmpty()) {
        loadProduk(); // Jika kosong, tampilkan semua produk
    } else {
        cariData(kunci); // Jika diisi, jalankan pencarian
    }
    }//GEN-LAST:event_txtCariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpanTransaksi;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblKeranjang;
    private static javax.swing.JTable tblProduk;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdTransaksi;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
  
    
    private void loadProduk() {
    DefaultTableModel model = (DefaultTableModel) tblProduk.getModel();
    model.setRowCount(0);

    try {
        Connection con = Koneksi.Go();
        String sql = "SELECT id_produk, nama_produk, ukuran, harga, stok FROM produk";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            Object[] row = {
                rs.getInt("id_produk"),
                rs.getString("nama_produk"),
                rs.getString("ukuran"),
                rs.getDouble("harga"),
                rs.getInt("stok")
            };
            model.addRow(row);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
  }

private void hitungTotal() {
    double total = 0;
    DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        String subtotalStr = model.getValueAt(i, 4).toString();
        subtotalStr = subtotalStr.replace(".", "")
                                 .replace(",", "");
        total += Double.parseDouble(subtotalStr);
    }

    lblTotal.setText("Total : Rp " + formatRupiah(total));
    lblTotal.revalidate();
    lblTotal.repaint();
}
private void initTransaksi() {
    txtTanggal.setText(
        java.time.LocalDate.now().toString()
    );
}
private String formatRupiah(double angka) {
    DecimalFormat df = new DecimalFormat("#,###");
    return df.format(angka);
}
private double ambilTotalDariLabel() {
    String totalStr = lblTotal.getText()
            .replace("Total : Rp", "")
            .replace(".", "")
            .replace(",", "")
            .trim();
    return Double.parseDouble(totalStr);
}
private void resetTransaksi() {
    DefaultTableModel model =
            (DefaultTableModel) tblKeranjang.getModel();
    model.setRowCount(0);

    lblTotal.setText("Total : Rp 0");
    txtJumlah.setText("");
        int idPelanggan = 0;
}
private void updateTotalKeuntungan() {
    double total = 0;
    DefaultTableModel model = (DefaultTableModel) tblKeranjang.getModel();
    
    for (int i = 0; i < model.getRowCount(); i++) {
        // Ambil nilai dari kolom Subtotal (asumsi kolom subtotal ada di indeks ke-4)
        // Sesuaikan angka 4 dengan urutan kolom subtotal Anda (0, 1, 2, 3, 4...)
        double subtotal = Double.parseDouble(model.getValueAt(i, 4).toString().replace("Rp ", "").replace(",", ""));
        total += subtotal;
    }
    
    // Tampilkan hasil ke label total
    lblTotal.setText("Rp " + String.format("%,.0f", total));
}
private void cariData(String kunci) {
    DefaultTableModel model = (DefaultTableModel) tblProduk.getModel();
    model.setRowCount(0);

    try {
        Connection con = Koneksi.Go();
        // Mencari berdasarkan nama produk menggunakan keyword LIKE
        String sql = "SELECT * FROM produk WHERE nama_produk LIKE ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, "%" + kunci + "%");
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] row = {
                rs.getInt("id_produk"),
                rs.getString("nama_produk"),
                rs.getString("ukuran"),
                rs.getDouble("harga"),
                rs.getInt("stok")
            };
            model.addRow(row);
        }
    } catch (SQLException e) {
        System.out.println("Error Cari: " + e.getMessage());
    }
}
private void setAutoID() {
    try {
        Connection con = Koneksi.Go();
        Statement st = con.createStatement();
        // Mencari ID transaksi terakhir
        String sql = "SELECT MAX(id_transaksi) FROM transaksi";
        ResultSet rs = st.executeQuery(sql);
        
        if (rs.next()) {
            int nextID = rs.getInt(1) + 1;
            txtIdTransaksi.setText(String.valueOf(nextID));
        } else {
            txtIdTransaksi.setText("1");
        }
        // Kunci kolom agar tidak bisa diedit manual
        txtIdTransaksi.setEditable(false); 
    } catch (SQLException e) {
        txtIdTransaksi.setText("1");
    }
}
}
