/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package szn;

/**
 *
 * @author ADVAN
 */
public class DashboardManager extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardManager.class.getName());

    /**
     * Creates new form DashboardManager
     */
    public DashboardManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        btnGrafikPenjualan = new javax.swing.JButton();
        btnPendapatan = new javax.swing.JButton();
        btnLaporanHarian = new javax.swing.JButton();
        btnProdukTerjual = new javax.swing.JButton();
        btnKinerjaKasir = new javax.swing.JButton();
        btnProdukTerlaris = new javax.swing.JButton();
        btnLaba = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setPreferredSize(new java.awt.Dimension(180, 420));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGrafikPenjualan.setBackground(new java.awt.Color(255, 255, 102));
        btnGrafikPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrafikPenjualan.setText("Grafik Penjualan");
        btnGrafikPenjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrafikPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafikPenjualanActionPerformed(evt);
            }
        });
        jPanel6.add(btnGrafikPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 180, 40));

        btnPendapatan.setBackground(new java.awt.Color(255, 255, 102));
        btnPendapatan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPendapatan.setText("Pendapatan");
        btnPendapatan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendapatanActionPerformed(evt);
            }
        });
        jPanel6.add(btnPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 180, 40));

        btnLaporanHarian.setBackground(new java.awt.Color(255, 255, 102));
        btnLaporanHarian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLaporanHarian.setText("Laporan Harian");
        btnLaporanHarian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporanHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanHarianActionPerformed(evt);
            }
        });
        jPanel6.add(btnLaporanHarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 180, 40));

        btnProdukTerjual.setBackground(new java.awt.Color(255, 255, 102));
        btnProdukTerjual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProdukTerjual.setText("Produk Terjual");
        btnProdukTerjual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdukTerjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukTerjualActionPerformed(evt);
            }
        });
        jPanel6.add(btnProdukTerjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 180, 40));

        btnKinerjaKasir.setBackground(new java.awt.Color(255, 255, 102));
        btnKinerjaKasir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKinerjaKasir.setText("Kinerja Kasir");
        btnKinerjaKasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKinerjaKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKinerjaKasirActionPerformed(evt);
            }
        });
        jPanel6.add(btnKinerjaKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 180, 40));

        btnProdukTerlaris.setBackground(new java.awt.Color(255, 255, 102));
        btnProdukTerlaris.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProdukTerlaris.setText("Produk Terlaris");
        btnProdukTerlaris.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdukTerlaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukTerlarisActionPerformed(evt);
            }
        });
        jPanel6.add(btnProdukTerlaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 180, 40));

        btnLaba.setBackground(new java.awt.Color(255, 255, 102));
        btnLaba.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLaba.setText("Laba");
        btnLaba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabaActionPerformed(evt);
            }
        });
        jPanel6.add(btnLaba, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 180, 40));

        panelContent.setBackground(new java.awt.Color(0, 153, 153));
        panelContent.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(0, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 226, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logout");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 60, 226, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrafikPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafikPenjualanActionPerformed

    }//GEN-LAST:event_btnGrafikPenjualanActionPerformed

    private void btnPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendapatanActionPerformed

    }//GEN-LAST:event_btnPendapatanActionPerformed

    private void btnLaporanHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanHarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaporanHarianActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnProdukTerjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukTerjualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdukTerjualActionPerformed

    private void btnKinerjaKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKinerjaKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKinerjaKasirActionPerformed

    private void btnProdukTerlarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukTerlarisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdukTerlarisActionPerformed

    private void btnLabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLabaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardManager().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrafikPenjualan;
    private javax.swing.JButton btnKinerjaKasir;
    private javax.swing.JButton btnLaba;
    private javax.swing.JButton btnLaporanHarian;
    private javax.swing.JButton btnPendapatan;
    private javax.swing.JButton btnProdukTerjual;
    private javax.swing.JButton btnProdukTerlaris;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
}
