/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package szn;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import sz.util.Koneksi;
import sz.util.Users;




public class LoginPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginPage.class.getName());

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Username");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 32, 134, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 76, 134, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 32, 248, 32));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 76, 248, 32));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setText("Login Now");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 126, 157, 33));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 454, 199));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1271, 726, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_sepatu.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Login();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    
    private void Login() {
    String usr = txtUsername.getText();
    // Gunakan getPassword() dan konversi ke String HANYA untuk perbandingan sementara.
    String pwd = new String(txtPassword.getPassword()); 
    
    // Gunakan try-with-resources untuk memastikan Connection dan PreparedStatement ditutup
    try (Connection K = Koneksi.Go();
         java.sql.PreparedStatement PS = K.prepareStatement(
             "SELECT id_user, nama, Email, Username, password FROM Users WHERE Username = ? AND password = ?"
         )) {
        
        PS.setString(1, usr); // Mengganti tanda tanya pertama (?) dengan nilai username
        PS.setString(2, pwd); // Mengganti tanda tanya kedua (?) dengan nilai password
        
        try (ResultSet RS = PS.executeQuery()) {
            int n = 0;
            Users Us = new Users();
            
            if (RS.next()) {
                Users.setId(RS.getInt("id_user"));
                Users.setNama(RS.getString("nama"));
                Users.setEmail(RS.getString("Email"));
                Users.setUsername(RS.getString("Username"));
                Users.setPassword(RS.getString("password"));

                this.dispose(); // TUTUP LOGIN

                DashboardAdmin DA = new DashboardAdmin();
                DA.setExtendedState(Frame.MAXIMIZED_BOTH);
                DA.setVisible(true);

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Username atau Password salah.");
            }

        }
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi error koneksi database:\n" + e.getMessage());
        logger.log(java.util.logging.Level.SEVERE, "SQL Error during login", e);
    }
    }
}
    
    
    


//    private void Login() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
//}
//    private void Login() {
//        String usr = txtUsername.getText();
//        String pwd = new String(txtPassword.getPassword());
//        try {
//            Connection K = Koneksi.Go();
//            Statement ST = K.createStatement();
//            String Q = "SELECT * FROM Users "
//                    + "WHERE "
//                    + "username='" + usr + "' AND "
//                    + "password='" + pwd + "'";
//            ResultSet RS = ST.executeQuery(Q);
//            int n = 0;
//            Users Usr = new Users();
//            while (RS.next()) {
//                n++;
//                Users.setId(RS.getInt("id_user"));
//                Users.setNama(RS.getString("nama"));
//                Users.setJabatan(RS.getString("email"));
//                Users.setUsername(RS.getString("username"));
//                Users.setPassword(RS.getString("password"));
//            }
//            if (n > 0) {
//                switch (Users.getUsername()) {
//                    case "kasir2" -> {
//                        this.setVisible(false);
//                        DashboardAdmin DA = new DashboardAdmin();
//                        DA.Users = Usr;
//                        DA.setVisible(true);
//                        DA.setExtendedState(Frame.MAXIMIZED_BOTH);
//                    }
//                    case "kasir1" -> {
//                    }
//                    case "admin" -> {
//                    }
//                    default -> {
//                    }
//                }
//                //kita redirect ke dashboard kasir
//                //kita redirect ke dashboard manajer
//                //opsional
//                            } else {
//                System.err.println("Akun tidak ditemukan");
//            }
//        } catch (SQLException e) {
//            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi error:\n" + e.getMessage());
//        }
//        
//        
//            
//        
//
//    }
//}